### PR TITLE
Moves Storage source files under Sources and Tests

### PR DESCRIPTION
**Pull request by brennanMKE**
*Issue #, if available:*

*Description of changes:*

Other categories have top level folders for Sources and Tests. This update matches this folder structure for Storage. See below for the new folder structure.

Storage Folders

*Check points: (check or cross out if not relevant)*

- [ ] Added new tests to cover change, if needed
- [ ] Build succeeds with all target using Swift Package Manager
- [ ] All unit tests pass
- [ ] All integration tests pass
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [ ] Documentation update for the change if required
- [ ] PR title conforms to conventional commit style
- [ ] If breaking change, documentation/changelog update with migration instructions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ruisebas** [comment]
How about also removing the `StoragePlugin.xcodeproj` and `Podfile` files? 
They are no longer needed, right?

**Review by ruisebas — APPROVED** [review]
How about also removing the `StoragePlugin.xcodeproj` and `Podfile` files? 
They are no longer needed, right?

**Review by lawmicha — APPROVED** [review]
LGTM
- you can delete the Podfile and Podfile.lock as well
- May be easier to remove HostApp completely, and recreate a new Application called StorageHostApp. Then add testing bundle targets, Copy Configuration Files build phase. in the integration testsing, we no long have access to AmplifyTestCommon so right now i copy the TestConfigHelper directly to the test target so that it can pick up the configuration files using Bundle.

**Comment by ruisebas** [comment]
@lawmicha Yeah I'm taking care of running the integration tests for Storage, so I'll handle that on a different PR :)

**Comment by brennanMKE** [comment]
> How about also removing the `StoragePlugin.xcodeproj` and `Podfile` files?
> They are no longer needed, right?

I will remove these files separately. We no longer use them now that SPM handles everything.

**Pull request merged**
