### PR TITLE
feat: Mark APIs that return operations with @discardableResult

### PR DESCRIPTION
**Pull request by palpatim**
Refs #628

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sebsto** [comment]
Thanks for adding this ! After I updated my project to 1.1.0, removing derived data and cleaning the build, I still receive the 'unsused' warning.  What do I miss ?

image

I am sure I have the correct version :

```swift
    @discardableResult
    func signIn(username: String?,
                password: String?,
                options: AuthSignInOperation.Request.Options?,
                listener: AuthSignInOperation.ResultListener?) -> AuthSignInOperation

```

**Comment by palpatim** [comment]
Hmm. Best guess is that I neglected to annotate one of the extension methods. Investigating.

**Comment by palpatim** [comment]
@sebsto Thanks for pointing this out. Tracking the fix in https://github.com/aws-amplify/amplify-ios/issues/713

**Comment by palpatim** [comment]
Fixed in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.1

**Pull request merged**
