### PR TITLE
chore: update SQLite dependency to 0.13.2

### PR DESCRIPTION
**Pull request by thisisabhash**
*Issue #, if available:* None

*Description of changes:* update SQLite dependency to 0.13.2

*Check points: (check or cross out if not relevant)*

~~- [ ] Added new tests to cover change, if needed~~
- [x] Build succeeds with all target using Swift Package Manager
- [x] All unit tests pass
- [x] All integration tests pass
- [x] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
~~- [ ] Documentation update for the change if required~~
- [x] PR title conforms to conventional commit style
~~- [ ] If breaking change, documentation/changelog update with migration instructions~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by lawmicha — CHANGES_REQUESTED** [review]
If the dependency version update for SQLite also applies to DataStore then we should re-run the integration tests to make sure nothing is broken. This change should also be applied to  DataStore in `main` at the same time to keep the code aligned as much as possible

**Comment by thisisabhash** [comment]
This change is already present on `main` : https://github.com/aws-amplify/amplify-ios/blob/2c4f85aa8c18bb67101422ca35dac708dbd49db4/Package.swift#L39

**Comment by thisisabhash** [comment]
Ran all unit tests and integration tests in my local machine. They're passing with this change.

**Review by lawmicha — APPROVED** [review]
LGTM

**Pull request merged**
